### PR TITLE
fix(ci): Sign kernel in images with ublue-os/kernel-signer

### PR DESCRIPTION
**Pull request by EyeCantCU**
Allows using our akmods key for SecureBoot

### CODE REVIEW

**Review by castrojo — APPROVED** [review]

**Review by m2Giles — APPROVED** [review]

**Comment by m2Giles** [comment]
Note, we need to still sign the coreos kernel. Instead of deleting it will just only run for those workflows

**Comment by m2Giles** [comment]
This is also g2g.

**Comment by bsherman** [comment]
I think we are closing this in favor of https://github.com/ublue-os/kernel-cache

**Comment by m2Giles** [comment]
Cached kernels implement in #265

**Pull request closed without merging**
